SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

PADDLE_DISTANCE_FROM_EDGE = 60

PADDLE_STRETCH_WIDTH = 5
PADDLE_WIDTH = 20 * PADDLE_STRETCH_WIDTH

PADDLE_STRETCH_LENGTH = 1
PADDLE_LENGTH = 20 * PADDLE_STRETCH_LENGTH

BALL_STRETCH_DIAMETER = 2
BALL_DIAMETER = 20 * BALL_STRETCH_DIAMETER
